# Generated by Django 5.2.8 on 2025-11-21 18:48

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی\u200c',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, unique=True, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('subject', models.CharField(max_length=250, verbose_name='موضوع')),
                ('like', models.IntegerField(default=0, verbose_name='لایک')),
                ('views', models.IntegerField(default=0, verbose_name='بازدید')),
                ('read', models.IntegerField(default=0, verbose_name='زمان خواندن')),
                ('search', models.CharField(max_length=250, unique=True, verbose_name='ادرس')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('created_date', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('updated_date', django_jalali.db.models.jDateField(auto_now=True, verbose_name='زمان اپدیت')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('categorys', models.ManyToManyField(related_name='articles', to='blog.category', verbose_name='دسته بندی\u200c\u200cها')),
                ('tags', models.ManyToManyField(related_name='articles', to='blog.tag', verbose_name='تگ ها')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقاله ها',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('comment', models.TextField(verbose_name='نظر')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('created_date', django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.article', verbose_name='مقاله')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
                'ordering': ('-id',),
            },
        ),
    ]
