# Generated by Django 5.2.8 on 2025-11-20 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comments_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('created_date',)},
        ),
    ]
