# Generated by Django 5.2.8 on 2025-11-20 19:17

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_comments_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={},
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_date',
            field=django_jalali.db.models.jDateField(auto_now_add=True, verbose_name='زمان ثبت'),
        ),
    ]
