# Generated by Django 5.2.8 on 2025-11-21 18:48

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news', verbose_name='عکس')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('read', models.IntegerField(default=0, verbose_name='زمان خواندن')),
                ('views', models.IntegerField(default=0, verbose_name='بازدید')),
                ('like', models.IntegerField(default=0, verbose_name='لایک')),
                ('search', models.CharField(max_length=250, verbose_name='ادرس')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('special', models.BooleanField(default=False, verbose_name='ویژه')),
                ('created_date', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='اپدیت')),
                ('updated_date', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='اپدیت')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'خبر',
                'verbose_name_plural': 'خبر\u200cها\u200c',
                'ordering': ('-id',),
            },
        ),
    ]
