# Generated by Django 5.2.8 on 2025-11-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='published_date',
        ),
    ]
